// Comprehensive shipping zones configuration
export const SHIPPING_ZONES = {
  UK: {
    name: "United Kingdom",
    countries: ["GB"],
    isDefault: false,
    description: "Domestic UK shipping",
  },
  EUROPE: {
    name: "Europe",
    countries: [
      "AD",
      "AL",
      "AT",
      "BA",
      "BE",
      "BG",
      "BY",
      "CH",
      "CY",
      "CZ",
      "DE",
      "DK",
      "EE",
      "ES",
      "FI",
      "FR",
      "GI",
      "GR",
      "HR",
      "HU",
      "IE",
      "IS",
      "IT",
      "LI",
      "LT",
      "LU",
      "LV",
      "MC",
      "MD",
      "ME",
      "MK",
      "MT",
      "NL",
      "NO",
      "PL",
      "PT",
      "RO",
      "RS",
      "SE",
      "SI",
      "SK",
      "SM",
      "UA",
      "VA",
      "XK",
    ],
    isDefault: false,
    description: "European Union and surrounding countries",
  },
  NORTH_AMERICA: {
    name: "North America",
    countries: [
      "US",
      "CA",
      "MX",
      "AG",
      "AI",
      "AW",
      "BB",
      "BL",
      "BM",
      "BQ",
      "BS",
      "BZ",
      "CR",
      "CU",
      "CW",
      "DM",
      "DO",
      "GD",
      "GL",
      "GP",
      "GT",
      "HN",
      "HT",
      "JM",
      "KN",
      "KY",
      "LC",
      "MF",
      "MQ",
      "MS",
      "NI",
      "PA",
      "PM",
      "PR",
      "SV",
      "SX",
      "TC",
      "TT",
      "VC",
      "VG",
      "VI",
    ],
    isDefault: false,
    description: "United States, Canada, Mexico and Caribbean",
  },
  ASIA_PACIFIC: {
    name: "Asia Pacific",
    countries: [
      "AU",
      "NZ",
      "JP",
      "KR",
      "SG",
      "HK",
      "TW",
      "MY",
      "TH",
      "PH",
      "ID",
      "VN",
      "IN",
      "CN",
      "BD",
      "PK",
      "LK",
      "MM",
      "KH",
      "LA",
      "BN",
      "MV",
      "BT",
      "NP",
      "AF",
      "MN",
      "KZ",
      "KG",
      "TJ",
      "TM",
      "UZ",
      "FJ",
      "PG",
      "SB",
      "VU",
      "NC",
      "PF",
      "WS",
      "TO",
      "TV",
      "KI",
      "NR",
      "PW",
      "FM",
      "MH",
      "AS",
      "GU",
      "MP",
      "CK",
      "NU",
      "TK",
      "WF",
      "PN",
    ],
    isDefault: false,
    description: "Asia, Australia, New Zealand and Pacific Islands",
  },
  MIDDLE_EAST: {
    name: "Middle East",
    countries: [
      "AE",
      "SA",
      "QA",
      "KW",
      "BH",
      "OM",
      "JO",
      "LB",
      "SY",
      "IQ",
      "IR",
      "IL",
      "PS",
      "YE",
      "AM",
      "AZ",
      "GE",
      "TR",
      "CY",
    ],
    isDefault: false,
    description: "Middle Eastern countries",
  },
  AFRICA: {
    name: "Africa",
    countries: [
      "ZA",
      "NG",
      "EG",
      "KE",
      "GH",
      "MA",
      "TN",
      "DZ",
      "AO",
      "MZ",
      "MG",
      "CM",
      "CI",
      "NE",
      "BF",
      "ML",
      "MW",
      "ZM",
      "SN",
      "SO",
      "TD",
      "GN",
      "RW",
      "BJ",
      "BI",
      "TN",
      "ER",
      "SL",
      "TG",
      "CF",
      "LR",
      "MR",
      "NA",
      "BW",
      "LS",
      "SZ",
      "GM",
      "GW",
      "DJ",
      "KM",
      "CV",
      "ST",
      "SC",
      "MU",
      "YT",
      "RE",
    ],
    isDefault: false,
    description: "African continent",
  },
  SOUTH_AMERICA: {
    name: "South America",
    countries: ["BR", "AR", "CL", "PE", "CO", "VE", "EC", "BO", "PY", "UY", "GY", "SR", "GF"],
    isDefault: false,
    description: "South American countries",
  },
  REST_OF_WORLD: {
    name: "Rest of World",
    countries: [],
    isDefault: true,
    description: "All other countries not covered by specific zones",
  },
} as const

export const SHIPPING_METHODS = {
  UK: [
    {
      name: "Royal Mail First Class",
      carrier: "Royal Mail",
      description: "Next working day delivery",
      icon: "Truck",
      basePrice: 3.99,
      freeShippingThreshold: 30,
      estimatedDelivery: "1-2 business days",
      weightSurcharges: [
        { minWeight: 0, maxWeight: 500, surcharge: 0 },
        { minWeight: 501, maxWeight: 1000, surcharge: 1.5 },
        { minWeight: 1001, maxWeight: 2000, surcharge: 3.0 },
      ],
    },
    {
      name: "Royal Mail Second Class",
      carrier: "Royal Mail",
      description: "Standard delivery service",
      icon: "Box",
      basePrice: 2.99,
      freeShippingThreshold: 25,
      estimatedDelivery: "2-3 business days",
      weightSurcharges: [
        { minWeight: 0, maxWeight: 500, surcharge: 0 },
        { minWeight: 501, maxWeight: 1000, surcharge: 1.0 },
        { minWeight: 1001, maxWeight: 2000, surcharge: 2.0 },
      ],
    },
    {
      name: "DPD Next Day",
      carrier: "DPD",
      description: "Guaranteed next working day delivery",
      icon: "Plane",
      basePrice: 6.99,
      freeShippingThreshold: 50,
      estimatedDelivery: "Next working day",
      weightSurcharges: [
        { minWeight: 0, maxWeight: 1000, surcharge: 0 },
        { minWeight: 1001, maxWeight: 5000, surcharge: 2.5 },
        { minWeight: 5001, maxWeight: 10000, surcharge: 5.0 },
      ],
    },
  ],
  EUROPE: [
    {
      name: "European Standard",
      carrier: "DHL",
      description: "Standard European delivery",
      icon: "Truck",
      basePrice: 8.99,
      freeShippingThreshold: 75,
      estimatedDelivery: "5-7 business days",
      weightSurcharges: [
        { minWeight: 0, maxWeight: 500, surcharge: 0 },
        { minWeight: 501, maxWeight: 1000, surcharge: 3.0 },
        { minWeight: 1001, maxWeight: 2000, surcharge: 6.0 },
      ],
    },
    {
      name: "European Express",
      carrier: "DHL",
      description: "Fast European delivery",
      icon: "Plane",
      basePrice: 15.99,
      freeShippingThreshold: 100,
      estimatedDelivery: "2-3 business days",
      weightSurcharges: [
        { minWeight: 0, maxWeight: 500, surcharge: 0 },
        { minWeight: 501, maxWeight: 1000, surcharge: 5.0 },
        { minWeight: 1001, maxWeight: 2000, surcharge: 10.0 },
      ],
    },
  ],
  NORTH_AMERICA: [
    {
      name: "North America Standard",
      carrier: "FedEx",
      description: "Standard delivery to North America",
      icon: "Truck",
      basePrice: 12.99,
      freeShippingThreshold: 100,
      estimatedDelivery: "7-10 business days",
      weightSurcharges: [
        { minWeight: 0, maxWeight: 500, surcharge: 0 },
        { minWeight: 501, maxWeight: 1000, surcharge: 5.0 },
        { minWeight: 1001, maxWeight: 2000, surcharge: 10.0 },
      ],
    },
    {
      name: "North America Express",
      carrier: "FedEx",
      description: "Express delivery to North America",
      icon: "Plane",
      basePrice: 24.99,
      freeShippingThreshold: 150,
      estimatedDelivery: "3-5 business days",
      weightSurcharges: [
        { minWeight: 0, maxWeight: 500, surcharge: 0 },
        { minWeight: 501, maxWeight: 1000, surcharge: 8.0 },
        { minWeight: 1001, maxWeight: 2000, surcharge: 15.0 },
      ],
    },
  ],
  ASIA_PACIFIC: [
    {
      name: "Asia Pacific Standard",
      carrier: "DHL",
      description: "Standard delivery to Asia Pacific",
      icon: "Truck",
      basePrice: 14.99,
      freeShippingThreshold: 100,
      estimatedDelivery: "10-14 business days",
      weightSurcharges: [
        { minWeight: 0, maxWeight: 500, surcharge: 0 },
        { minWeight: 501, maxWeight: 1000, surcharge: 6.0 },
        { minWeight: 1001, maxWeight: 2000, surcharge: 12.0 },
      ],
    },
    {
      name: "Asia Pacific Express",
      carrier: "DHL",
      description: "Express delivery to Asia Pacific",
      icon: "Plane",
      basePrice: 29.99,
      freeShippingThreshold: 150,
      estimatedDelivery: "5-7 business days",
      weightSurcharges: [
        { minWeight: 0, maxWeight: 500, surcharge: 0 },
        { minWeight: 501, maxWeight: 1000, surcharge: 10.0 },
        { minWeight: 1001, maxWeight: 2000, surcharge: 20.0 },
      ],
    },
  ],
  MIDDLE_EAST: [
    {
      name: "Middle East Standard",
      carrier: "Aramex",
      description: "Standard delivery to Middle East",
      icon: "Truck",
      basePrice: 16.99,
      freeShippingThreshold: 120,
      estimatedDelivery: "8-12 business days",
      weightSurcharges: [
        { minWeight: 0, maxWeight: 500, surcharge: 0 },
        { minWeight: 501, maxWeight: 1000, surcharge: 7.0 },
        { minWeight: 1001, maxWeight: 2000, surcharge: 14.0 },
      ],
    },
    {
      name: "Middle East Express",
      carrier: "Aramex",
      description: "Express delivery to Middle East",
      icon: "Plane",
      basePrice: 32.99,
      freeShippingThreshold: 180,
      estimatedDelivery: "4-6 business days",
      weightSurcharges: [
        { minWeight: 0, maxWeight: 500, surcharge: 0 },
        { minWeight: 501, maxWeight: 1000, surcharge: 12.0 },
        { minWeight: 1001, maxWeight: 2000, surcharge: 24.0 },
      ],
    },
  ],
  AFRICA: [
    {
      name: "Africa Standard",
      carrier: "DHL",
      description: "Standard delivery to Africa",
      icon: "Truck",
      basePrice: 18.99,
      freeShippingThreshold: 120,
      estimatedDelivery: "12-18 business days",
      weightSurcharges: [
        { minWeight: 0, maxWeight: 500, surcharge: 0 },
        { minWeight: 501, maxWeight: 1000, surcharge: 8.0 },
        { minWeight: 1001, maxWeight: 2000, surcharge: 16.0 },
      ],
    },
    {
      name: "Africa Express",
      carrier: "DHL",
      description: "Express delivery to Africa",
      icon: "Plane",
      basePrice: 35.99,
      freeShippingThreshold: 200,
      estimatedDelivery: "6-10 business days",
      weightSurcharges: [
        { minWeight: 0, maxWeight: 500, surcharge: 0 },
        { minWeight: 501, maxWeight: 1000, surcharge: 15.0 },
        { minWeight: 1001, maxWeight: 2000, surcharge: 30.0 },
      ],
    },
  ],
  SOUTH_AMERICA: [
    {
      name: "South America Standard",
      carrier: "FedEx",
      description: "Standard delivery to South America",
      icon: "Truck",
      basePrice: 19.99,
      freeShippingThreshold: 150,
      estimatedDelivery: "14-21 business days",
      weightSurcharges: [
        { minWeight: 0, maxWeight: 500, surcharge: 0 },
        { minWeight: 501, maxWeight: 1000, surcharge: 9.0 },
        { minWeight: 1001, maxWeight: 2000, surcharge: 18.0 },
      ],
    },
    {
      name: "South America Express",
      carrier: "FedEx",
      description: "Express delivery to South America",
      icon: "Plane",
      basePrice: 39.99,
      freeShippingThreshold: 200,
      estimatedDelivery: "7-10 business days",
      weightSurcharges: [
        { minWeight: 0, maxWeight: 500, surcharge: 0 },
        { minWeight: 501, maxWeight: 1000, surcharge: 18.0 },
        { minWeight: 1001, maxWeight: 2000, surcharge: 35.0 },
      ],
    },
  ],
  REST_OF_WORLD: [
    {
      name: "International Standard",
      carrier: "DHL",
      description: "Standard international delivery",
      icon: "Truck",
      basePrice: 22.99,
      freeShippingThreshold: 150,
      estimatedDelivery: "15-25 business days",
      weightSurcharges: [
        { minWeight: 0, maxWeight: 500, surcharge: 0 },
        { minWeight: 501, maxWeight: 1000, surcharge: 10.0 },
        { minWeight: 1001, maxWeight: 2000, surcharge: 20.0 },
      ],
    },
    {
      name: "International Express",
      carrier: "DHL",
      description: "Express international delivery",
      icon: "Plane",
      basePrice: 45.99,
      freeShippingThreshold: 250,
      estimatedDelivery: "7-12 business days",
      weightSurcharges: [
        { minWeight: 0, maxWeight: 500, surcharge: 0 },
        { minWeight: 501, maxWeight: 1000, surcharge: 20.0 },
        { minWeight: 1001, maxWeight: 2000, surcharge: 40.0 },
      ],
    },
  ],
} as const

// Country code to name mapping for display purposes
export const COUNTRY_NAMES: Record<string, string> = {
  // Europe
  AD: "Andorra",
  AL: "Albania",
  AT: "Austria",
  BA: "Bosnia and Herzegovina",
  BE: "Belgium",
  BG: "Bulgaria",
  BY: "Belarus",
  CH: "Switzerland",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DE: "Germany",
  DK: "Denmark",
  EE: "Estonia",
  ES: "Spain",
  FI: "Finland",
  FR: "France",
  GB: "United Kingdom",
  GI: "Gibraltar",
  GR: "Greece",
  HR: "Croatia",
  HU: "Hungary",
  IE: "Ireland",
  IS: "Iceland",
  IT: "Italy",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  MC: "Monaco",
  MD: "Moldova",
  ME: "Montenegro",
  MK: "North Macedonia",
  MT: "Malta",
  NL: "Netherlands",
  NO: "Norway",
  PL: "Poland",
  PT: "Portugal",
  RO: "Romania",
  RS: "Serbia",
  SE: "Sweden",
  SI: "Slovenia",
  SK: "Slovakia",
  SM: "San Marino",
  UA: "Ukraine",
  VA: "Vatican City",
  XK: "Kosovo",

  // North America
  US: "United States",
  CA: "Canada",
  MX: "Mexico",
  AG: "Antigua and Barbuda",
  AI: "Anguilla",
  AW: "Aruba",
  BB: "Barbados",
  BL: "Saint Barthélemy",
  BM: "Bermuda",
  BQ: "Bonaire, Sint Eustatius and Saba",
  BS: "Bahamas",
  BZ: "Belize",
  CR: "Costa Rica",
  CU: "Cuba",
  CW: "Curaçao",
  DM: "Dominica",
  DO: "Dominican Republic",
  GD: "Grenada",
  GL: "Greenland",
  GP: "Guadeloupe",
  GT: "Guatemala",
  HN: "Honduras",
  HT: "Haiti",
  JM: "Jamaica",
  KN: "Saint Kitts and Nevis",
  KY: "Cayman Islands",
  LC: "Saint Lucia",
  MF: "Saint Martin",
  MQ: "Martinique",
  MS: "Montserrat",
  NI: "Nicaragua",
  PA: "Panama",
  PM: "Saint Pierre and Miquelon",
  PR: "Puerto Rico",
  SV: "El Salvador",
  SX: "Sint Maarten",
  TC: "Turks and Caicos Islands",
  TT: "Trinidad and Tobago",
  VC: "Saint Vincent and the Grenadines",
  VG: "British Virgin Islands",
  VI: "U.S. Virgin Islands",

  // Asia Pacific
  AU: "Australia",
  NZ: "New Zealand",
  JP: "Japan",
  KR: "South Korea",
  SG: "Singapore",
  HK: "Hong Kong",
  TW: "Taiwan",
  MY: "Malaysia",
  TH: "Thailand",
  PH: "Philippines",
  ID: "Indonesia",
  VN: "Vietnam",
  IN: "India",
  CN: "China",
  BD: "Bangladesh",
  PK: "Pakistan",
  LK: "Sri Lanka",
  MM: "Myanmar",
  KH: "Cambodia",
  LA: "Laos",
  BN: "Brunei",
  MV: "Maldives",
  BT: "Bhutan",
  NP: "Nepal",
  AF: "Afghanistan",
  MN: "Mongolia",
  KZ: "Kazakhstan",
  KG: "Kyrgyzstan",
  TJ: "Tajikistan",
  TM: "Turkmenistan",
  UZ: "Uzbekistan",
  FJ: "Fiji",
  PG: "Papua New Guinea",
  SB: "Solomon Islands",
  VU: "Vanuatu",
  NC: "New Caledonia",
  PF: "French Polynesia",
  WS: "Samoa",
  TO: "Tonga",
  TV: "Tuvalu",
  KI: "Kiribati",
  NR: "Nauru",
  PW: "Palau",
  FM: "Micronesia",
  MH: "Marshall Islands",
  AS: "American Samoa",
  GU: "Guam",
  MP: "Northern Mariana Islands",
  CK: "Cook Islands",
  NU: "Niue",
  TK: "Tokelau",
  WF: "Wallis and Futuna",
  PN: "Pitcairn",

  // Middle East
  AE: "United Arab Emirates",
  SA: "Saudi Arabia",
  QA: "Qatar",
  KW: "Kuwait",
  BH: "Bahrain",
  OM: "Oman",
  JO: "Jordan",
  LB: "Lebanon",
  SY: "Syria",
  IQ: "Iraq",
  IR: "Iran",
  IL: "Israel",
  PS: "Palestine",
  YE: "Yemen",
  AM: "Armenia",
  AZ: "Azerbaijan",
  GE: "Georgia",
  TR: "Turkey",

  // Africa
  ZA: "South Africa",
  NG: "Nigeria",
  EG: "Egypt",
  KE: "Kenya",
  GH: "Ghana",
  MA: "Morocco",
  TN: "Tunisia",
  DZ: "Algeria",
  AO: "Angola",
  MZ: "Mozambique",
  MG: "Madagascar",
  CM: "Cameroon",
  CI: "Côte d'Ivoire",
  NE: "Niger",
  BF: "Burkina Faso",
  ML: "Mali",
  MW: "Malawi",
  ZM: "Zambia",
  SN: "Senegal",
  SO: "Somalia",
  TD: "Chad",
  GN: "Guinea",
  RW: "Rwanda",
  BJ: "Benin",
  BI: "Burundi",
  ER: "Eritrea",
  SL: "Sierra Leone",
  TG: "Togo",
  CF: "Central African Republic",
  LR: "Liberia",
  MR: "Mauritania",
  NA: "Namibia",
  BW: "Botswana",
  LS: "Lesotho",
  SZ: "Eswatini",
  GM: "Gambia",
  GW: "Guinea-Bissau",
  DJ: "Djibouti",
  KM: "Comoros",
  CV: "Cape Verde",
  ST: "São Tomé and Príncipe",
  SC: "Seychelles",
  MU: "Mauritius",
  YT: "Mayotte",
  RE: "Réunion",

  // South America
  BR: "Brazil",
  AR: "Argentina",
  CL: "Chile",
  PE: "Peru",
  CO: "Colombia",
  VE: "Venezuela",
  EC: "Ecuador",
  BO: "Bolivia",
  PY: "Paraguay",
  UY: "Uruguay",
  GY: "Guyana",
  SR: "Suriname",
  GF: "French Guiana",
}

// Helper function to get zone for a country
export function getZoneForCountry(countryCode: string): string {
  for (const [zoneKey, zone] of Object.entries(SHIPPING_ZONES)) {
    if (zone.countries.includes(countryCode)) {
      return zoneKey
    }
  }
  return "REST_OF_WORLD" // Default zone
}

// Helper function to get shipping methods for a zone
export function getShippingMethodsForZone(zoneKey: string) {
  return SHIPPING_METHODS[zoneKey as keyof typeof SHIPPING_METHODS] || SHIPPING_METHODS.REST_OF_WORLD
}
